# Generated by Django 2.2.16 on 2020-10-06 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Swiped',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField(verbose_name='当前用户id')),
                ('sid', models.IntegerField(verbose_name='被滑的用户id')),
                ('stype', models.CharField(choices=[('like', '喜欢'), ('superlike', '超级喜欢'), ('dislike', '不喜欢')], max_length=9, verbose_name='滑动类型')),
                ('stime', models.DateTimeField(auto_now_add=True, verbose_name='滑动的时间')),
            ],
            options={
                'db_table': 'slide_record',
                'unique_together': {('user_id', 'sid')},
            },
        ),
        migrations.CreateModel(
            name='Friend',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id1', models.IntegerField()),
                ('user_id2', models.IntegerField()),
            ],
            options={
                'unique_together': {('user_id1', 'user_id2')},
            },
        ),
    ]
