# Generated by Django 2.2.16 on 2020-09-26 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserApp', '0002_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='gender',
            field=models.CharField(choices=[('male', '男'), ('female', '女'), ('unknow', '未知')], default='male', max_length=10, verbose_name='性别'),
        ),
        migrations.AlterField(
            model_name='user',
            name='location',
            field=models.CharField(default='上海', max_length=10, verbose_name='常居地'),
        ),
    ]
